# Autogenerated by devscripts/update-version.py

__version__ = '2023.04.02.172328'

RELEASE_GIT_HEAD = '25fc8bc7e2f1f30629200e8bdf1ab70ccac08665'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'stable'
